import Layout from "@/components/Layout/Layout";
import Hero from "@/components/Hero/Hero";
import Head from "next/head";
import { Box } from "@chakra-ui/react";
import { Flex } from "@chakra-ui/react";
import MentorImage from "@/components/MentorImage";
import AboutYouStep from "@/components/AboutYouStep";
import ApplyingMentor from "@/components/ApplyingMentor";
import CheckboxCustomGroup from "@/components/CheckboxCustomGroup";
import MentorPropertys from "@/components/MentorPropertys";

export default function Home() {
  return (
    <>
      <Head>
        <title>DevMentor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Hero />
      </Layout>
    </>
  );
}
