import Layout from "@/components/Layout/Layout";
import Head from "next/head";

import MentorCard from "@/components/MentorCard";
import { Flex, Grid } from "@chakra-ui/react";

export default function Home() {
  return (
    <>
      <Head>
        <title>DevMentor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div>
          <Flex
            gap="2"
            display="flex"
            alignItems="center"
            justifyContent="center"
          >
            <MentorCard />
            <MentorCard />
            <MentorCard />
          </Flex>
        </div>
      </Layout>
    </>
  );
}
