name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Using Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: latest

      - name: "Create env file"
        run: |
          touch .env
          echo NEXT_PUBLIC_BACKEND_URL=https://devmentor-b.fly.dev >> .env
          echo FLY_API_TOKEN=${{ secrets.FLY_API_TOKEN }} >> .env
          cat .env
      - name: Deploy to Fly
        run: printenv && flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
